### ISSUE TITLE
As a [user] I want to navigate to my profile page and see a personalized record

### ISSUE THREAD

**Issue by jlusthaus** [nightowlsnode/nightowlsnode#2]

**Comment by BMCooley** [comment]
-user page component

-bio component
-should pull user info from bd
-should display that info in a editable state
-info tracking should update on a button click

-items component
-shouyld  get users itmes from db
-should be able to add to user items
-should be able to remove items
-item tracking view should update dynamically

**Comment by BMCooley** [comment]
suggest splitting bio and items component between 2 people
